# Generated by Django 2.0.5 on 2018-06-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
