# Generated by Django 2.0.5 on 2018-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180627_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professors', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='professor',
            name='degree',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
