# Generated by Django 2.0.5 on 2018-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180703_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
